#pragma once

#define SPEAKER 2
#define RELAY 3
#define DHT_SENSOR 4
#define LEFT_WING_SW_1 24
#define LEFT_WING_SW_2 22
#define RIGHT_WING_SW_1 26
#define RIGHT_WING_SW_2 28
#define PUMP_SW_1 30
#define PUMP_SW_2 32
#define PUSH_BTN_VALVE 34
#define PUSH_BTN_AUTO_PUMP 36
#define PUSH_BTN_RESET 38
#define LEFT_WING_LEFT_LED 31
#define LEFT_WING_RIGHT_LED 33
#define RIGHT_WING_LEFT_LED 35
#define RIGHT_WING_RIGHT_LED 37
#define PUMP_OFF_LED 39
#define RESET_LED 41
#define VALVE_ON_LED 43
#define AUTO_PUMP_ON_LED 45
#define PUMP_ON_LED 47